title: Adhitya's blog 
author: Adhitya Srinivasan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"

# social links
twitter_username: @AdhityaSriniva5
github_username:  GummyBear1820

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-merlot
